# Generated by Django 2.2.4 on 2022-08-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
