# Generated by Django 2.2.4 on 2022-08-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0006_auto_20220809_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='User',
            new_name='user',
        ),
    ]
