# Generated by Django 2.2.4 on 2022-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0007_auto_20220809_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.CharField(max_length=10)),
                ('time_spent', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='labels',
            new_name='labels_list',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='reportee',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='watchers',
            new_name='watchers_list',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='name',
            new_name='title',
        ),
    ]
