# Generated by Django 2.2.4 on 2022-08-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0009_auto_20220810_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='owner',
        ),
    ]
